name: Build XC16 Firmware with Custom Makefile

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and install XC16 v2.10
        run: |
          wget https://github.com/Weisni/R1-1-P1_1-C1-1/releases/download/1.1/xc16-v2.10.run
          chmod +x xc16-v2.10.run
          ./xc16-v2.10.run --mode unattended --prefix /opt/microchip/xc16 --netservername localhost || true

      - name: Build firmware using custom Makefile
        run: |
          PATH="/opt/microchip/xc16/v2.10/bin:$PATH" make -f Makefile.custom

      - name: Upload HEX file
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/firmware.hex
