name: Build XC16 Firmware with submodules

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules (using PAT)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_PAT }}

      - name: Download and extract XC16 toolchain
        run: |
          wget https://github.com/Weisni/R1-1-P1_1-C1-1/releases/download/1.2/xc16-v2.10-bin.zip
          unzip xc16-v2.10-bin.zip -d xc16

      - name: Upload extracted toolchain
        uses: actions/upload-artifact@v4
        with:
          name: xc16-toolchain
          path: xc16

  build:
    runs-on: windows-latest
    needs: prepare

    steps:
      - name: Checkout repository with submodules (using PAT)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_PAT }}

      - name: Download XC16 toolchain
        uses: actions/download-artifact@v4
        with:
          name: xc16-toolchain
          path: ${{ github.workspace }}/xc16

      - name: Run GitVersion prebuild
        run: |
          powershell -ExecutionPolicy Bypass -File "$pwd\\GitVersion\\GitVersion.ps1"
        shell: powershell

      - name: Build firmware
        run: |
          $env:Path = "$pwd\\xc16\\v2.10\\bin;$env:Path"
          make -f Makefile.custom
        shell: powershell

      - name: Run CopyHexfile postbuild
        run: |
          powershell -ExecutionPolicy Bypass -File "$pwd\\GitVersion\\CopyHexfile.ps1"
        shell: powershell

      - name: Upload versioned HEX files
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: Hex/**
