on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # 🐧 Job 1: Toolchain vorbereiten (Linux)
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and extract XC16 toolchain
        run: |
          wget https://github.com/Weisni/R1-1-P1_1-C1-1/releases/download/1.2/xc16-v2.10-bin.zip
          unzip xc16-v2.10-bin.zip -d xc16

      - name: Upload extracted toolchain
        uses: actions/upload-artifact@v4
        with:
          name: xc16-toolchain
          path: xc16

  # 🪟 Job 2: Build Firmware (Windows)
  build:
    runs-on: windows-latest
    needs: prepare  # ⬅️ wartet auf "prepare"-Job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download toolchain from prepare job
        uses: actions/download-artifact@v4
        with:
          name: xc16-toolchain
          path: xc16

      - name: Install GNU Make
        run: |
          choco install make -y
        shell: powershell

      - name: Set PATH and build firmware
        run: |
          $env:Path = "$pwd\xc16\v2.10\bin;$env:Path"
          make -f Makefile.custom
        shell: powershell

      - name: Upload all HEX outputs
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: Hex/**
