name: Build XC16 Firmware on Windows

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install GNU Make
        run: choco install make -y
        shell: powershell

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and extract XC16 v2.10
        run: |
          Invoke-WebRequest -Uri "https://github.com/Weisni/R1-1-P1_1-C1-1/releases/download/1.2/xc16-v2.10-bin.zip" -OutFile "xc16.zip"
          Expand-Archive xc16.zip -DestinationPath "xc16"
        shell: powershell

      - name: Build firmware using custom Makefile
        run: |
          $env:Path = "$pwd\xc16\v2.10\bin;" + $env:Path
          make -f Makefile.custom
        shell: powershell

      - name: Upload HEX file
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/firmware.hex
