name: Build XC16 Firmware

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget unzip

    - name: Install Microchip XC16 Compiler v1.70
      run: |
        wget https://ww1.microchip.com/downloads/en/DeviceDoc/xc16-v1.70-full-install-linux-installer.run
        chmod +x xc16-v1.70-full-install-linux-installer.run
        ./xc16-v1.70-full-install-linux-installer.run --mode unattended --prefix /opt/microchip/xc16
        echo "/opt/microchip/xc16/v1.70/bin" >> $GITHUB_PATH

    - name: Build MPLABX Project
      run: |
        make CONF=Release

    - name: Upload HEX file
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: dist/Release/production/*.hex
